[MakeQuestionsConfig]
model_name = "gpt-oss:20b"
temperature = 0.7
max_tokens = 150
top_p = 1.0
frequency_penalty = 0.0
presence_penalty = 0.0
max_words_per_text = 350
retries = 10
cache = "~/.make_questions_cache.cache"

[NLIBatchingChukingConfig]
model_name = "MoritzLaurer/mDeBERTa-v3-base-xnli-multilingual-nli-2mil7"
batch_size = 8 # Number of documents per batch
chunk_size = 350 # Number of words per chunk
overlap = 50 #  Word overlap between chunks
max_chunks_per_minibatch = 64 # Texts that are too long might need to be subdivided in minibatches
max_characters_per_chunk = 2000 # Maximum number of characters per chunk (avoids spurious sequences without spaces)
device = 'auto' # auto = gpu if available, else cpu
label_names=["entailment", "neutral", "contradiction"] # Order of labels (depends on the model)

[SamplingConfig]
selection_strategy = "kmeans"  # e.g., 'random', 'vote_k', 'kmeans'
n_select = 14
k_neighbors = 30 # Number of neighbors for VoteKSampler
seed = 42
use_gpu = true # Use GPU foi FAISS kmeans
niter = 50
spherical = true

[NLISamplingConfig]
n_select = 0.1

[TextEmbeddingConfig]
model_name = "sentence-transformers/all-mpnet-base-v2"
device = "auto"  # 'auto', 'cpu', or 'cuda'
chunk_size = 100
overlap = 25
cache = "~/.text_embedding_cache"

[LabelPropagationConfig]
n_neighbors = 10
sigma = 1.0
alpha = 0.99
max_iter = 100
tol = 1e-3