"""Integration test demonstrating the exact use case from Issue #8."""

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from askme.rtp import TreeNode, evaluate_exploratory_power


def test_issue_8_use_case():
    """
    Test the exact use case described in Issue #8:
    - Function receives the tree (as: the root TreeNode) and labels as inputs
    - Calculates 'Node Purity' for every leaf
    - Calculates 'Isolation Depth' for each class
    """
    # Create a sample tree with a realistic structure
    # This simulates a tree that might be generated by RTPBuilder
    root = TreeNode(
        documents=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        question="Is this about technology?"
    )
    
    # Left branch: tech-related (documents 0-4)
    left = TreeNode(
        documents=[0, 1, 2, 3, 4],
        question="Is it about software?"
    )
    
    # Right branch: non-tech (documents 5-9)
    right = TreeNode(
        documents=[5, 6, 7, 8, 9],
        question="Is it about nature?"
    )
    
    root.left = left
    root.right = right
    
    # Further split left branch
    left_left = TreeNode(documents=[0, 1, 2])  # Software
    left_right = TreeNode(documents=[3, 4])     # Hardware
    left.left = left_left
    left.right = left_right
    
    # Further split right branch
    right_left = TreeNode(documents=[5, 6])    # Plants
    right_right = TreeNode(documents=[7, 8, 9])  # Animals
    right.left = right_left
    right.right = right_right
    
    # Define manually-generated labels (aligned with document indexes)
    # Class 0: Software (docs 0, 1, 2)
    # Class 1: Hardware (docs 3, 4)
    # Class 2: Plants (docs 5, 6)
    # Class 3: Animals (docs 7, 8, 9)
    labels = [0, 0, 0, 1, 1, 2, 2, 3, 3, 3]
    
    # This is the main function from Issue #8
    results = evaluate_exploratory_power(root, labels)
    
    # Verify that Node Purity is calculated for every leaf
    assert 'leaf_purities' in results
    assert len(results['leaf_purities']) == 4  # 4 leaf nodes
    
    # Verify that all purities are 1.0 (perfectly separated)
    for leaf_id, purity in results['leaf_purities'].items():
        assert purity == 1.0, f"Leaf {leaf_id} should be pure but has purity {purity}"
    
    # Verify that Isolation Depth is calculated for each class
    assert 'isolation_depths' in results
    assert len(results['isolation_depths']) == 4  # 4 classes
    
    # Verify isolation depths are reasonable
    # All classes should be isolated at depth 2 (the leaf level in this tree)
    for class_label, depth in results['isolation_depths'].items():
        assert depth is not None, f"Class {class_label} should be isolated"
        assert depth == 2, f"Class {class_label} should be isolated at depth 2 but is at {depth}"
    
    print("✓ Issue #8 use case test passed!")
    print(f"  - Node Purity calculated for {results['num_leaves']} leaves")
    print(f"  - Isolation Depth calculated for {len(results['isolation_depths'])} classes")
    print(f"  - Average leaf purity: {results['average_leaf_purity']:.2f}")


def test_issue_8_with_imperfect_separation():
    """
    Test with a tree that has imperfect separation (more realistic scenario).
    """
    root = TreeNode(documents=[0, 1, 2, 3, 4, 5])
    left = TreeNode(documents=[0, 1, 2])
    right = TreeNode(documents=[3, 4, 5])
    
    root.left = left
    root.right = right
    
    # Mixed classes in leaves (imperfect separation)
    # Left has mostly class 0, but one class 1
    # Right has mostly class 1, but one class 0
    labels = [0, 0, 1, 1, 1, 0]
    
    results = evaluate_exploratory_power(root, labels)
    
    # Verify node purities are calculated
    assert len(results['leaf_purities']) == 2
    
    # Both leaves should have purity < 1.0 (not perfectly pure)
    for leaf_id, purity in results['leaf_purities'].items():
        assert 0.0 <= purity < 1.0
    
    # Verify isolation depths
    # Neither class is fully isolated in this tree
    assert results['isolation_depths'][0] is None
    assert results['isolation_depths'][1] is None
    
    print("✓ Issue #8 imperfect separation test passed!")
    print(f"  - Average leaf purity: {results['average_leaf_purity']:.4f} (< 1.0 as expected)")
    print(f"  - Classes 0 and 1 are not isolated (as expected)")


if __name__ == "__main__":
    print("=" * 60)
    print("Testing Issue #8 Requirements")
    print("=" * 60)
    print()
    
    print("Test 1: Perfect separation")
    print("-" * 60)
    test_issue_8_use_case()
    print()
    
    print("Test 2: Imperfect separation")
    print("-" * 60)
    test_issue_8_with_imperfect_separation()
    print()
    
    print("=" * 60)
    print("All Issue #8 tests passed! ✓")
    print("=" * 60)
