from pydantic import BaseModel
from typing import Optional

class TreeNode(BaseModel):
    documents: list[int]  # Indices of documents in this node
    left: Optional['TreeNode'] = None  # Left child node
    right: Optional['TreeNode'] = None  # Right child node
    #parent: Optional['TreeNode'] = None  # Parent node
    question: Optional[str] = None  # Question used to split this node


TreeNode.model_rebuild()

class TokenUsage(BaseModel):
    total_tokens: int = 0
    prompt_tokens: int = 0
    completion_tokens: int = 0

class SplitMetrics(BaseModel):
    """
    Metrics collected during RTPBuilder execution.
    
    This class tracks various performance and usage statistics when the
    RTPBuilder processes a document collection. Use return_metrics=True
    when calling RTPBuilder to obtain these metrics.
    
    Attributes:
        llm_input_tokens: Number of tokens sent to the LLM for hypothesis generation
        llm_output_tokens: Number of tokens generated by the LLM
        nli_calls: Number of times the NLI model was called to check entailment
        faiss_search_time_ms: Time (in milliseconds) spent on FAISS indexing and embedding
        label_propagation_time_ms: Time (in milliseconds) spent propagating labels
        total_time_ms: Total execution time (in milliseconds)
        split_ratio: Proportion of documents in the left child (0.0 if no split occurs)
        medoid_nli_confidence_avg: Average NLI confidence on selected medoid documents
        llm_request_time: Time (in milliseconds) spent on LLM calls
        nli_time: Time (in milliseconds) spent on NLI calls
    """
    llm_input_tokens: int = 0
    llm_output_tokens: int = 0
    nli_calls: int = 0
    faiss_search_time_ms: float = 0.0
    label_propagation_time_ms: float = 0.0
    total_time_ms: float = 0.0
    split_ratio: float = 0.0
    medoid_nli_confidence_avg: float = 0.0
    llm_request_time: float = 0.0
    nli_time: float = 0.0